#!/bin/bash

# Fast Universal Gentoo Instalation Script - Created by Realist - (c) 2024 v 1.3
# Hyprland Perfect Desktop Project - EFI F2FS SSD Version with LTO PGO GCC and PYTHON

# VARIABLES
NOW=date +'%m%d%H%M%Y'
TARGET_DISK=/dev/sda
TARGET_LAN=eno1
GENTOO_ROOT_PASSWORD=toor
GENTOO_USER=realist
GENTOO_USER_PASSWORD=toor
GENTOO_HOSTNAME=hyprland
GENTOO_DOMAINNAME=gentoo.dev
GENTOO_INSTALLER_URL=http://94.113.201.164:55/hyprland
#GENTOO_INSTALLER_URL=https://github.com/lotrando/realist-hyprland-desktop/blob/main
GRUB_GFX_MODE=1920x1080x32
GENTOO_KEYMAP=us
GENTOO_CONSOLEFONT=ter-v16b
GENTOO_ZONEINFO=Europe/Prague

# DATE
date ${NOW}

# DISK SETUP
parted -s ${TARGET_DISK} mklabel gpt
parted -a optimal ${TARGET_DISK} << END
unit mib
mkpart primary fat32 1 150
name 1 UEFI
set 1 bios_grub on
mkpart primary 150 -1
name 2 ROOT
p
quit
END


# DISK FILESYSTEM
yes | mkfs.fat -n UEFI -F32 ${TARGET_DISK}1
yes | mkfs.f2fs -l ROOT -O extra_attr,inode_checksum,sb_checksum -f ${TARGET_DISK}2
mkdir -p /mnt/gentoo
mount -t f2fs ${TARGET_DISK}2 /mnt/gentoo
mkdir -p /mnt/gentoo/boot
mount ${TARGET_DISK}1 /mnt/gentoo/boot


# STAGE3 & PORTAGE
cd /mnt/gentoo
wget https://distfiles.gentoo.org/releases/amd64/autobuilds/20240526T163557Z/stage3-amd64-openrc-20240526T163557Z.tar.xz
tar xpf stage3-amd64-openrc-20240526T163557Z.tar.xz --xattrs-include='*.*' --numeric-owner
mkdir -p /mnt/gentoo/var/db/repos/gentoo
mkdir -p /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/
cp /etc/resolv.conf /mnt/gentoo/etc/
rm /mnt/gentoo/stage3*

# MOUNTING SYSTEM FS
mount -t proc none /mnt/gentoo/proc
mount -t sysfs none /mnt/gentoo/sys
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --rbind /run /mnt/gentoo/run
mount --make-rslave /mnt/gentoo/run
test -L /dev/shm && rm /dev/shm && mkdir /dev/shm
mount --types tmpfs --options nosuid,nodev,noexec shm /dev/shm
chmod 1777 /dev/shm

# CHROOT - CONFIG SETUP AND START INSTALL PACKAGES
cat > /mnt/gentoo/root/gentoo-chroot.sh << END
#!/bin/bash

emerge-webrsync
cd /etc/portage/
rm make.conf
rm -R package.use
rm -R package.accept_keywords
rm -R package.mask
wget -q $GENTOO_INSTALLER_URL/make.conf
wget -q $GENTOO_INSTALLER_URL/package.accept_keywords
wget -q $GENTOO_INSTALLER_URL/package.use
wget -q $GENTOO_INSTALLER_URL/package.license
wget -q $GENTOO_INSTALLER_URL/package.mask

cat >> /etc/fstab << IEND
${TARGET_DISK}1   /boot   vfat    noatime      0 2
${TARGET_DISK}2   /       f2fs    defaults,rw  0 0
IEND

sed -i 's/localhost/$GENTOO_HOSTNAME/g' /etc/conf.d/hostname
sed -i 's/default8x16/$GENTOO_CONSOLEFONT/g' /etc/conf.d/consolefont
echo "127.0.0.1 $GENTOO_HOSTNAME.$GENTOO_DOMAINNAME $GENTOO_HOSTNAME localhost" >> /etc/hosts
sed -i 's/127.0.0.1/#127.0.0.1/g' /etc/hosts

#sed -i 's/us/$GENTOO_KEYMAP/g' /etc/conf.d/keymaps

cat >> /etc/locale.gen << IEND
cs_CZ.UTF-8 UTF-8
cs_CZ ISO-8859-2
IEND

cat >> /etc/env.d/02locale << IEND
LANG="cs_CZ.UTF-8"
LC_COLLATE="C"
IEND

locale-gen
echo "$GENTOO_ZONEINFO" > /etc/timezone
env-update && source /etc/profile

echo "root:$GENTOO_ROOT_PASSWORD" | chpasswd -c SHA256
useradd -m -G audio,video,usb,cdrom,portage,users,wheel,input -s /bin/bash $GENTOO_USER
echo "$GENTOO_USER:$GENTOO_USER_PASSWORD" | chpasswd -c SHA256

# ----------------------------------------------------------------------------

#emerge gentoo-kernel-bin
emerge -g genkernel linux-firmware zen-sources && genkernel all

emerge -g dhcpcd grub os-prober terminus-font sudo f2fs-tools ntfs3g dev-vcs/git eselect-repository

eselect repository enable mv && emaint sync -r mv
eselect repository enable guru && emaint sync -r guru

emerge -gNDU @world

emerge -g seatd hyprland hyprpaper hyprpicker hyprland-contrib xdg-desktop-portal-hyprland waybar rofi-wayland wlogout grim slurp kitty pipewire

emerge -g oh-my-zsh gentoo-zsh-completions zsh-completions usbutils pciutils eza btop app-misc/mc faenza-icon-theme adwaita-qt qt5ct fira-code roboto ubuntu-font-family neofetch eix gentoolkit tumbler thunar firefox imagemagick nwg-look pavucontrol audacious mpv virtualbox ristretto --noreplace nano
git clone https://github.com/romkatv/powerlevel10k.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# ----------------------------------------------------------------------------

cat >> /etc/default/grub << IEND
GRUB_GFXMODE=$GRUB_GFX_MODE
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_BACKGROUND="/boot/grub/grub.png"
GRUB_DISABLE_OS_PROBER=false
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
IEND

sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

chsh -s /bin/zsh root
chsh -s /bin/zsh $GENTOO_USER

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=HYPRLAND --recheck ${TARGET_DISK}
cd /boot/grub
wget -q $GENTOO_INSTALLER_URL/grub.png
grub-mkconfig -o /boot/grub/grub.cfg

rc-update add elogind boot && rc-update add consolefont default && rc-update add numlock default
rc-update add sshd default && rc-update add dbus default && rc-update add dhcpcd default

##################
# WEB DEVELOPERS #
##################

emerge -g phpmyadmin dev-db/mysql dev-lang/php nodejs composer vscode sublime-text
rm -R /usr/lib/tmpfiles.d/mysql.conf

cat >> /usr/lib/tmpfiles.d/mysql.conf << IEND
d /run/mysqld 0755 mysql mysql -
IEND

cd /home/realist
wget -q $GENTOO_INSTALLER_URL/.bash_profile
wget -q $GENTOO_INSTALLER_URL/.bashrc
wget -q $GENTOO_INSTALLER_URL/.zlogin
wget -q $GENTOO_INSTALLER_URL/.zshrc
wget -q $GENTOO_INSTALLER_URL/.p10k.zsh

chown -R $GENTOO_USER:$GENTOO_USER /home/$GENTOO_USER

sed -i 's/SSL_DEFAULT_VHOST/PHP/g' /etc/conf.d/apache2
echo "ServerName localhost" >> /etc/apache2/httpd.conf
rm -R /var/www/localhost/htdocs/index.html
echo "<?php phpinfo(); ?>" > /var/www/localhost/htdocs/index.php
cp /var/www/localhost/htdocs/phpmyadmin/config.sample.inc.php /var/www/localhost/htdocs/phpmyadmin/config.inc.php
mkdir /var/www/localhost/htdocs/phpmyadmin/tmp/
chown -R apache:apache /var/www/
usermod -aG apache $GENTOO_USER
chmod -R 775 /var/www/localhost/htdocs
chmod -R 777 /var/www/localhost/htdocs/phpmyadmin/tmp
echo "#cfg['blowfish_secret'] = 'WntN0150l71sLq/{w4V0:ZXFv7WcB-Qz';" >> /var/www/localhost/htdocs/phpmyadmin/config.inc.php
rc-update add apache2 default && rc-update add mysql default
emerge --config mysql

rm -R /root/gentoo-chroot.sh
END

chmod +x /mnt/gentoo/root/gentoo-chroot.sh
chroot /mnt/gentoo /root/gentoo-chroot.sh
