#!/bin/bash

# Fast Universal Gentoo Instalation Script - Created by Realist - (c) 2024 v 1.3
# RMS - Realist Minimized Starter - EFI F2FS SSD Version with LTO PGO

# VARIABLES
TARGET_DISK=/dev/sda
TARGET_LAN=enp0s3
GENTOO_ROOT_PASSWORD=toor
GENTOO_USER=realist
GENTOO_USER_PASSWORD=toor
GENTOO_HOSTNAME=starter
GENTOO_DOMAINNAME=gentoo.dev
GENTOO_INSTALLER_URL=https://raw.githubusercontent.com/lotrando/realist-hyprland-desktop/main
GENTOO_INSTALLER_URL=http://94.113.201.164:55/hyprland
GRUB_GFX_MODE=1920x1080x32
GENTOO_KEYMAP=us
GENTOO_CONSOLEFONT=ter-v16b
GENTOO_ZONEINFO=Europe/Prague

# DISK SETUP
parted -s ${TARGET_DISK} mklabel gpt
parted -a optimal ${TARGET_DISK} << END
unit mib
mkpart primary fat32 1 150
name 1 UEFI
set 1 bios_grub on
mkpart primary 150 -1
name 2 ROOT
p
quit
END


# DISK FILESYSTEM
yes | mkfs.fat -n UEFI -F32 ${TARGET_DISK}1
yes | mkfs.f2fs -l ROOT -O extra_attr,inode_checksum,sb_checksum -f ${TARGET_DISK}2
mkdir -p /mnt/gentoo
mount -t f2fs ${TARGET_DISK}2 /mnt/gentoo
mkdir -p /mnt/gentoo/boot
mount ${TARGET_DISK}1 /mnt/gentoo/boot


# STAGE3 & PORTAGE
cd /mnt/gentoo
wget https://distfiles.gentoo.org/releases/amd64/autobuilds/20240602T164858Z/stage3-amd64-openrc-20240602T164858Z.tar.xz
tar xpf stage3-amd64-openrc-20240602T164858Z.tar.xz --xattrs-include='*.*' --numeric-owner
mkdir -p /mnt/gentoo/var/db/repos/gentoo
mkdir -p /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/
cp /etc/resolv.conf /mnt/gentoo/etc/
rm /mnt/gentoo/stage3*

# MOUNTING SYSTEM FS
mount -t proc none /mnt/gentoo/proc
mount -t sysfs none /mnt/gentoo/sys
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --rbind /run /mnt/gentoo/run
mount --make-rslave /mnt/gentoo/run
test -L /dev/shm && rm /dev/shm && mkdir /dev/shm
mount --types tmpfs --options nosuid,nodev,noexec shm /dev/shm
chmod 1777 /dev/shm

# CHROOT - CONFIG SETUP AND START INSTALL PACKAGES
cat > /mnt/gentoo/root/gentoo-chroot.sh << END
#!/bin/bash

emerge-webrsync

cd /etc/portage/
rm make.conf && rm -R package.use && rm -R package.accept_keywords && rm -R package.mask

cat >> /etc/portage/make.conf << IEND
# RMS - Realist Minimized Starter - EFI F2FS SSD Version with LTO PGO
# make.conf file (c) 2024 -> /etc/portage/make.conf
# (c) 2024

USE="nls"

CPU_FLAGS_X86=""
CFLAGS="-O2 -pipe -fomit-frame-pointer"
CXXFLAGS="-O2 -pipe -fomit-frame-pointer"
FCFLAGS="-O2 -pipe -fomit-frame-pointer"
FFLAGS="-O2 -pipe -fomit-frame-pointer"
MAKE_OPTS="-j6"

GENTOO_MIRRORS="https://mirror.dkm.cz/gentoo/"
PORTAGE_BINHOST="http://94.113.201.164:55/hyprland"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_NICENESS=19
PORTAGE_IONICE_COMMAND="ionice -c 3 -p \${PID}"
EMERGE_DEFAULT_OPTS="-v --ask-enter-invalid --jobs=4 --load-average=4"
FEATURES="buildpkg parallel-fetch"

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="-* @FREE"
GRUB_PLATFORMS="pc efi-64"

L10N="cs"

INPUT_DEVICES="libinput"
VIDEO_CARDS="amdgpu radeonsi vmware"
IEND

cat >> /etc/portage/package.accept_keywords << IEND
# RHMD
# Realist Hyperland Minimal Desktop LTO & GPO version
# package.accept_keywords file (c) 2024 -> /etc/portage/package.accept_keywords
# (c) 2024

# APP-MISC
app-misc/ca-certificates ~amd64

# APP-SHELLS
app-shells/oh-my-zsh ~amd64
app-shells/zsh-autosuggestions ~amd64
app-shells/zsh-syntax-highlighting ~amd64

# DEV-UTIL
dev-util/rocm-smi ~amd64

# SYS-APSS
sys-apps/eza ~amd64

# SYS-KERNEL
sys-kernel/zen-sources ~amd64
IEND

cat >> /etc/portage/package.use << IEND
# RHMD
# Realist Hyperland Minimal Desktop LTO & GPO version
# package.use file (c) 2024 -> /etc/portage/package.use
# (c) 2024

*/* PYTHON_TARGETS: python3_11 python3_12
*/* PYTHON_SINGLE_TARGET: -python3_11 python3_12

# APP-MISC
app-misc/mc -slang unicode gpm sftp

# DEV-LANG
dev-lang/python pgo

# MEDIA-FONTS
media-fonts/terminus-font -ru-g

# SYS-BOOT
sys-boot/grub mount

# SYS-KERNEL
sys-kernel/installkernel dracut
sys-kernel/linux-firmware initramfs
sys-kernel/zen-sources symlink
IEND

cat >> /etc/portage/package.license << IEND
# RHMD
# Realist Hyperland Minimal Desktop LTO & GPO version
# package.license file (c) 2024 -> /etc/portage/package.license
# (c) 2024

# SYS-KERNEL
sys-kernel/linux-firmware linux-fw-redistributable no-source-code
IEND

cat >> /etc/portage/package.mask << IEND
# RHMD
# Realist Hyperland Minimal Desktop LTO & GPO version
# package.mask file (c) 2024 -> /etc/portage/package.mask
# (c) 2024
IEND

cat >> /etc/fstab << IEND
${TARGET_DISK}1   /boot   vfat    noatime      0 2
${TARGET_DISK}2   /       f2fs    defaults,rw  0 0
IEND

sed -i 's/localhost/$GENTOO_HOSTNAME/g' /etc/conf.d/hostname
sed -i 's/default8x16/$GENTOO_CONSOLEFONT/g' /etc/conf.d/consolefont
echo "127.0.0.1 $GENTOO_HOSTNAME.$GENTOO_DOMAINNAME $GENTOO_HOSTNAME localhost" >> /etc/hosts
sed -i 's/127.0.0.1/#127.0.0.1/g' /etc/hosts
sed -i 's/us/$GENTOO_KEYMAP/g' /etc/conf.d/keymaps

cat >> /etc/locale.gen << IEND
cs_CZ.UTF-8 UTF-8
cs_CZ ISO-8859-2
IEND

locale-gen

echo "$GENTOO_ZONEINFO" > /etc/timezone
env-update && source /etc/profile

# ----------------------------------------------------------------------------

emerge linux-firmware && emerge gentoo-kernel-bin
#emerge genkernel linux-firmware zen-sources && genkernel all
emerge dhcpcd grub os-prober elogind sys-apps/dbus terminus-font sudo f2fs-tools app-misc/mc dev-vcs/git eselect-repository
#emerge -ND @world

# eselect repository enable mv && emaint sync -r mv && emerge --oneshot sys-apps/portage
# emerge oh-my-zsh gentoo-zsh-completions zsh-completions usbutils pciutils eza btop app-misc/mc faenza-icon-theme adwaita-qt qt5ct fira-code roboto ubuntu-font-family neofetch eix gentoolkit tumbler thunar firefox imagemagick nwg-look pavucontrol audacious mpv virtualbox ristretto --noreplace nano
# git clone https://github.com/romkatv/powerlevel10k.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/themes/powerlevel10k
# git clone https://github.com/zsh-users/zsh-autosuggestions.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /usr/share/zsh/site-contrib/oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# ----------------------------------------------------------------------------

cat >> /etc/default/grub << IEND
GRUB_GFXMODE=$GRUB_GFX_MODE
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_BACKGROUND="/boot/grub/grub.png"
GRUB_DISABLE_OS_PROBER=false
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
IEND

sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers

useradd -m -G audio,video,usb,cdrom,portage,users,wheel,input -s /bin/bash $GENTOO_USER
echo "root:$GENTOO_ROOT_PASSWORD" | chpasswd -c SHA256
echo "$GENTOO_USER:$GENTOO_USER_PASSWORD" | chpasswd -c SHA256

# chsh -s /bin/zsh $GENTOO_USER

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GENTOO --recheck ${TARGET_DISK}
cd /boot/grub
wget -q $GENTOO_INSTALLER_URL/grub.png
grub-mkconfig -o /boot/grub/grub.cfg

rc-update add consolefont default && rc-update add numlock default
rc-update add sshd default && rc-update add dhcpcd default
rc-update add elogind boot && rc-update add dbus default

cd /home/realist
git clone https://github.com/lotrando/realist-hyprland-desktop-rice.git
chown -R $GENTOO_USER:$GENTOO_USER /home/$GENTOO_USER

rm -R /root/gentoo-chroot.sh
END

chmod +x /mnt/gentoo/root/gentoo-chroot.sh
chroot /mnt/gentoo /root/gentoo-chroot.sh
